services:
    # Nullify this service. It is deprecated and raises an error on SensioLabs Insight
    twig.extension.actions:
        class: AppBundle\Twig\NullExtension

    twig.extensions.semester:
        class: AppBundle\Twig\SemesterExtension
        arguments: ["@doctrine.orm.default_entity_manager"]
        tags:
            - { name: twig.extension }

    twig.extensions.domain:
        class: AppBundle\Twig\DomainExtension
        arguments: ["%base_host%"]
        tags:
            - { name: twig.extension }

    app.notification_manager:
        class: AppBundle\Service\NotificationManager
        arguments: ['@mailer', '@twig']
